baseurl = "https://michaelpaulschramm.com/"
languageCode = "en-us"
title = "Mike's Notebook"
theme = "hugo-tint"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/About/"
[[menu.main]]
    name = "CV"
    url = "/CV/CV.pdf"

[params]
    description = "A blog for Michael Schramm"
    googleAnalytics = "UA-71354421-1"
    showPoweredBy = false
    copyrightHolder = "Michael Schramm"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", "python"]
    highlightjsTheme = "obsidian"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "/images/logo.png"
    width = 320
    height = 137
    alt = "Logo"
    [[params.social]]
    name = "Email"
    icon = "envelope"
    link = "mailto:mpschramm@gmail.com"
    [[params.social]]
    name = "GitHub"
    icon = "github"
    link = "https://github.com/mps9506"
    [[params.social]]
    name = "Twitter"
    icon = "twitter"
    link = "https://twitter.com/MPSchramm"
    [[params.social]]
    name = "LinkedIn"
    icon = "linkedin-square"
    link = "https://www.linkedin.com/in/schrammm/"
    [[params.social]]
    name = "Instagram"
    icon = "instagram"
    link = "https://www.instagram.com/bluelight.mike/"

