name = "hugo-tint"
license = "MIT"
licenselink = "https://github.com/mps9506/blogdown-tufte/blob/master/LICENSE.md"
description = "Hugo theme motivated by tint [tint is not tufte] (https://github.com/eddelbuettel/tint) and intended for use with R blogdown."
homepage = "https://github.com/mps9506/blogdown-tufte"
tags = ["blogdown", "tufte", "minimal"]
features = ["math", "tufte-css", "tufte"]
min_version = 0.01

[author]
  name = "Michael Schramm"
  homepage = "http://michaelpaulschramm.com"
